permalink: /:title/

exclude: [CNAME, compass.rb, Gemfile, Gemfile.lock, Guardfile, sass, javascripts, templates, README.md]

auto: true

base_path: help.lognit.com

# Build settings
markdown: kramdown
highlighter:      rouge

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
